### ISSUE TITLE
Decide on how to distribute.

### ISSUE THREAD

**Issue by psteiger** [DiscordTime/sticky-sessions-ios#25]
We need to figure out how to distribute the MVP when it's ready. Probably, all of them involve signing the app and cost money.

This StackOverflow question might be a good kickstart to the discussion.

https://stackoverflow.com/questions/43535693/private-ios-app

**Comment by psteiger** [comment]
It would be interesting to know how this works:

https://punchcard.cesar.org.br/downloads/ios.html

**Comment by CarlosRodrigo** [comment]
We are using [Firebase App Distribution](https://firebase.google.com/products/app-distribution) now. We can close this issue now that the app is on App Distribution.

There is another [issue](https://github.com/DiscordTime/sticky-sessions-ios/issues/51) to work on automatically deploying to App Distribution.
