### ISSUE TITLE
Authenticate using Google Sign-In

### ISSUE THREAD

**Issue by rodrigoperazzo** [DiscordTime/sticky-sessions-ios#26]
Authenticate with Firebase using user's Google Accounts by integrating Google Sign-In and Firebase Auth.

- [ ] Integrate Google Sign-in to the app. https://developers.google.com/identity/sign-in/ios/start

- [ ] Add Firebase to the project. https://firebase.google.com/docs/ios/setup

- [ ] Store Firebase JWT Token in order to send in the HTTP header of requests that are protected on server api.

**Comment by CarlosRodrigo** [comment]
Closing because #28 was merged.
